import Head from 'next/head'
import Feed from '../components/Feed';

import Header from '../components/Header';
import Modal from '../components/Modal';

// Takeaway: Do not using helper with-tailwindcss example project for next js. 
// Follow nextjs docs for adding tailwindcss and it will work smoothly.
// https://tailwindcss.com/docs/guides/nextjs

export default function Home() {
  return (
    <div className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Modal */}
      <Modal />

      {/* Header */}
      <Header />

      {/* Feed */}
      <Feed />

    </div>
  )
}
