export const jobs = [
  {
    company: 'Photosnap',
    new: true,
    featured: true,
    position: 'Senior Frontend Developer',
    meta: {
      duration: '1d ago',
      type: 'Full Time',
      location: 'USA only',
    },
    role: 'Frontend',
    level: 'Senior',
    skills: ['HTML', 'CSS', 'JavaScript'],
    logo: 'photosnap.svg',
  },
  {
    company: 'Manage',
    new: true,
    featured: true,
    position: 'Fullstack Developer',
    meta: {
      duration: '1d ago',
      type: 'Part Time',
      location: 'Remote',
    },
    role: 'Fullstack',
    level: 'Midweight',
    skills: ['Python', 'React'],
    logo: 'manage.svg',
  },
  {
    company: 'Account',
    new: true,
    featured: false,
    position: 'Junior Frontend Developer',
    meta: {
      duration: '2d ago',
      type: 'Part Time',
      location: 'USA Only',
    },
    role: 'Frontend',
    level: 'Junior',
    skills: ['JavaScript', 'React', 'Sass'],
    logo: 'account.svg',
  },
  {
    company: 'MyHome',
    new: false,
    featured: false,
    position: 'Junior Frontend Developer',
    meta: {
      duration: '5d ago',
      type: 'Contract',
      location: 'USA Only',
    },
    role: 'Frontend',
    level: 'Junior',
    skills: ['CSS', 'JavaScript'],
    logo: 'myhome.svg',
  },
  {
    company: 'Loop Studios',
    new: false,
    featured: false,
    position: 'Software Engineer',
    meta: {
      duration: '1w ago',
      type: 'Full Time',
      location: 'Worldwide',
    },
    role: 'Fullstack',
    level: 'Midweight',
    skills: ['JavaScript', 'Ruby', 'Sass'],
    logo: 'loop-studios.svg',
  },
  {
    company: 'FaceIt',
    new: false,
    featured: false,
    position: 'Junior Backend Developer',
    meta: {
      duration: '2w ago',
      type: 'Full Time',
      location: 'UK only',
    },
    role: 'Backend',
    level: 'Junior',
    skills: ['Ruby', 'RoR'],
    logo: 'faceit.svg',
  },
  {
    company: 'Shortly',
    new: false,
    featured: false,
    position: 'Junior Backend Developer',
    meta: {
      duration: '2w ago',
      type: 'Full Time',
      location: 'Worldwide',
    },
    role: 'Frontend',
    level: 'Junior',
    skills: ['HTML', 'JavaScript', 'Sass'],
    logo: 'shortly.svg',
  },
  {
    company: 'Insure',
    new: false,
    featured: false,
    position: 'Junior Frontend Developer',
    meta: {
      duration: '2w ago',
      type: 'Full Time',
      location: 'USA only',
    },
    role: 'Frontend',
    level: 'Junior',
    skills: ['JavaScript', 'Vue', 'Sass'],
    logo: 'insure.svg',
  },
  {
    company: 'Eyecam Co.',
    new: false,
    featured: false,
    position: 'Full Stack Engineer',
    meta: {
      duration: '3w ago',
      type: 'Full Time',
      location: 'Worldwide',
    },
    role: 'Fullstack',
    level: 'Midweight',
    skills: ['JavaScript', 'Python', 'Django'],
    logo: 'eyecam-co.svg',
  },
  {
    company: 'The Air Filter Company',
    new: false,
    featured: false,
    position: 'Front-end Dev',
    meta: {
      duration: '1m ago',
      type: 'Part Time',
      location: 'Worldwide',
    },
    role: 'Frontend',
    level: 'Junior',
    skills: ['JavaScript', 'React', 'Sass'],
    logo: 'the-air-filter-company.svg',
  },
];